/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIB;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *Klass som enbart innehåller knappar för att öppna nya klasser
 * @author Adam
 */
public class AgentFonster extends javax.swing.JFrame {

    private InfDB idb;
    private InlogAgent nyAgent;
    
    
    /**
     * Creates new form AgentFonster
     */
    public AgentFonster(InfDB idb, InlogAgent nyAgent) {
        initComponents();
        setValkommen(InlogAgent.getEpost());
        this.idb = idb;  
        this.nyAgent = nyAgent;
    }
    
    public AgentFonster(InfDB idb)
    {
        initComponents();
        this.idb = idb;
        setValkommen(InlogAgent.getEpost());
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLvalkommen = new javax.swing.JLabel();
        btnAndraLosen = new javax.swing.JButton();
        btnHanteraAlien = new javax.swing.JButton();
        btnRegUtr = new javax.swing.JButton();
        btnSokOChef = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAvsluta = new javax.swing.JToggleButton();
        btnAndraLosen1 = new javax.swing.JButton();
        btnSeutrustning = new javax.swing.JToggleButton();
        btnKvittera = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLvalkommen.setText("Välkommen Agent");

        btnAndraLosen.setText("Ändra lösenord");
        btnAndraLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenActionPerformed(evt);
            }
        });

        btnHanteraAlien.setText("Hantera alien");
        btnHanteraAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHanteraAlienActionPerformed(evt);
            }
        });

        btnRegUtr.setText("Registrera ny utrustning");
        btnRegUtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegUtrActionPerformed(evt);
            }
        });

        btnSokOChef.setText("Sök områdeschef");
        btnSokOChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokOChefActionPerformed(evt);
            }
        });

        jLabel1.setText("Åtgärder");

        btnAvsluta.setText("Logga ut");
        btnAvsluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvslutaActionPerformed(evt);
            }
        });

        btnAndraLosen1.setText("Sök Alien");
        btnAndraLosen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosen1ActionPerformed(evt);
            }
        });

        btnSeutrustning.setText("Se din utrustning");
        btnSeutrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeutrustningActionPerformed(evt);
            }
        });

        btnKvittera.setText("Kvittera utrustning");
        btnKvittera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKvitteraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAndraLosen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSokOChef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAndraLosen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHanteraAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegUtr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSeutrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKvittera, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLvalkommen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(178, 178, 178))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAvsluta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JLvalkommen)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraLosen)
                    .addComponent(btnSeutrustning))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHanteraAlien)
                    .addComponent(btnKvittera))
                .addGap(12, 12, 12)
                .addComponent(btnRegUtr)
                .addGap(12, 12, 12)
                .addComponent(btnSokOChef)
                .addGap(12, 12, 12)
                .addComponent(btnAndraLosen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnAvsluta)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //öppnar fönstret för att ändra lösenord
    private void btnAndraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenActionPerformed
        // TODO add your handling code here:
        new AndraLosenordFonster(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAndraLosenActionPerformed

    private void btnHanteraAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraAlienActionPerformed
        // TODO add your handling code here:
        new HanteraAliensFonster(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHanteraAlienActionPerformed

    private void btnRegUtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegUtrActionPerformed
        // TODO add your handling code here:
        new RegNyUtrustning(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegUtrActionPerformed

    private void btnSokOChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokOChefActionPerformed
        // TODO add your handling code here:
        new SokOmradeschef(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSokOChefActionPerformed

    private void btnAvslutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvslutaActionPerformed
        // TODO add your handling code here:
        
        //tömmer InlogAgent fält för att ny kan lagras vid inloggning
        nyAgent.loggaUt();
        new InloggningsFonster(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAvslutaActionPerformed

    private void btnAndraLosen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosen1ActionPerformed
        // TODO add your handling code here:
        new ValjTypSokAvAlien(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAndraLosen1ActionPerformed

    private void btnSeutrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeutrustningActionPerformed
        // TODO add your handling code here:
        new AgentUtrustningFonster(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSeutrustningActionPerformed

    private void btnKvitteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKvitteraActionPerformed
        // TODO add your handling code here:
        new KvitteringUtrustningAgent(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKvitteraActionPerformed

    private void setValkommen(String namn)
    {
        if(namn!=null){
            JLvalkommen.setText("Välkommen "+InlogAgent.getNamn());
        }
        else{
            JLvalkommen.setText("Välkommen agent");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLvalkommen;
    private javax.swing.JButton btnAndraLosen;
    private javax.swing.JButton btnAndraLosen1;
    private javax.swing.JToggleButton btnAvsluta;
    private javax.swing.JButton btnHanteraAlien;
    private javax.swing.JToggleButton btnKvittera;
    private javax.swing.JButton btnRegUtr;
    private javax.swing.JToggleButton btnSeutrustning;
    private javax.swing.JButton btnSokOChef;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
