/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIB;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author adamrosing
 */
public class AgentUtrustningFonster extends javax.swing.JFrame {
    
    private InfDB idb;

    /**
     * Creates new form AgentUtrustningFonster
     */
    public AgentUtrustningFonster(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitel = new javax.swing.JLabel();
        btnListautrustning = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBoxUtrustning = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitel.setText("För att se den utrustning du har just nu, tryck på knappen:");

        btnListautrustning.setText("Lista utrustning");
        btnListautrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListautrustningActionPerformed(evt);
            }
        });

        txtBoxUtrustning.setColumns(20);
        txtBoxUtrustning.setRows(5);
        jScrollPane1.setViewportView(txtBoxUtrustning);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnListautrustning)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLtitel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnTillbaka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLtitel)
                .addGap(18, 18, 18)
                .addComponent(btnListautrustning)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTillbaka)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListautrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListautrustningActionPerformed
        
        //hämtar den inloggade agentens epost
        String agentEpost = InlogAgent.getEpost();
        //sql fraga som hämtar benämning och även attribut från teknik, vapen och kommuniktaion
        //använder LEFT join på för att tillåta null värden ifall de enbart har en utrustning
        //registrerad under annan kategori
        String fraga = "SELECT utrustning.Benamning,vapen.Kaliber, kommunikation.Overforingsteknik, teknik.Kraftkalla, Utkvitteringsdatum " +
                       "FROM agent " +
                       "JOIN innehar_utrustning ON agent.agent_id = innehar_utrustning.Agent_ID " +
                       "JOIN utrustning ON innehar_utrustning.Utrustnings_ID = utrustning.Utrustnings_ID " +
                       "LEFT JOIN vapen ON utrustning.Utrustnings_ID = vapen.Utrustnings_ID " +
                       "LEFT JOIN kommunikation ON utrustning.Utrustnings_ID = kommunikation.Utrustnings_ID " +
                       "LEFT JOIN teknik ON utrustning.Utrustnings_ID = teknik.Utrustnings_ID WHERE agent.epost='"+agentEpost+"'";
        
        try{
            //hämtar raderna från fråga
            ArrayList<HashMap<String, String>> aktivUtr = idb.fetchRows(fraga);
            
            //ifall inget hämtades har inte agenten någon utkvitterad utrustning
            if(aktivUtr.isEmpty()){
                txtBoxUtrustning.setText("Du har ingen aktiv utrustning utkvitterad");
            }
            else{
                //loopar genom listan
                for(HashMap<String, String> rad : aktivUtr)
                {
                    String utrBenamning = rad.get("Benamning");
                    String kaliber = rad.get("Kaliber");
                    String ovrfTeknik = rad.get("Overforingsteknik");
                    String kraftK = rad.get("Kraftkalla");
                    String datum = rad.get("Utkvitteringsdatum");
                    
                    //System kontroll för att se vad som hämtats
                    System.out.println(utrBenamning+" "+kaliber+" "+ ovrfTeknik+" "+kraftK+" "+datum);
                
                    
                    
                    txtBoxUtrustning.append("Utrustningsbenämning: "+utrBenamning+"\n");
                    
                    //kontroll för att skriva ut attribut beroende på vilket kategori utrustningen hör till
                    if(kaliber != null){
                        txtBoxUtrustning.append("Kategori: Vapen"+"\n");
                        txtBoxUtrustning.append("Vapenkaliber: "+kaliber+"\n");
                    }
                    else if(ovrfTeknik != null){
                        txtBoxUtrustning.append("Kategori: Kommunikation"+"\n");
                        txtBoxUtrustning.append("Typ av teknik: "+ovrfTeknik+"\n");
                    }
                    else if(kraftK != null){
                        txtBoxUtrustning.append("Kategori: Teknik"+"\n");
                        txtBoxUtrustning.append("Typ av kraftkälla: "+kraftK+"\n");
                    }
                    txtBoxUtrustning.append("Utkvitteringsdatum: "+datum+"\n");
                    txtBoxUtrustning.append("-------------------------"+"\n");
                    
                }    
            }
        }catch(InfException ex){
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt felmeddelande"+ex.getMessage());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt fel: " + e);
        }
        
        
    }//GEN-LAST:event_btnListautrustningActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        new AgentFonster(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnListautrustning;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLtitel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtBoxUtrustning;
    // End of variables declaration//GEN-END:variables
}
