/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIB;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author adamrosing
 */
public class RedigeraAgentFonster extends javax.swing.JFrame {

    private InfDB idb;
    
    
    
    /**
     * Creates new form RedigeraAgentFonster
     */
    public RedigeraAgentFonster(InfDB idb) {
        initComponents();
        this.idb = idb;
        setLocationRelativeTo(null);
        laddaAgenter();
        laddaOmraden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitel = new javax.swing.JLabel();
        jLnamn = new javax.swing.JLabel();
        jLepost = new javax.swing.JLabel();
        jLtelefon = new javax.swing.JLabel();
        jLansDatum = new javax.swing.JLabel();
        jLlosenord = new javax.swing.JLabel();
        jLlosenord1 = new javax.swing.JLabel();
        txtfEpost = new javax.swing.JTextField();
        txtfNamn = new javax.swing.JTextField();
        txtfTelefon = new javax.swing.JTextField();
        txtfDatum = new javax.swing.JTextField();
        txtfLosen = new javax.swing.JTextField();
        cbxOmrade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLvalAgent = new javax.swing.JLabel();
        cbxAgenter = new javax.swing.JComboBox<>();
        btnHamtainfo = new javax.swing.JButton();
        jLnuvomrade = new javax.swing.JLabel();
        txtfNuvomrade = new javax.swing.JTextField();
        btnBekrafta = new javax.swing.JToggleButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLtitel.setText("Redigera information om en befintlig agent");

        jLnamn.setText("Namn:");

        jLepost.setText("E-post:");

        jLtelefon.setText("Telefon:");

        jLansDatum.setText("Anställningsdatum:");

        jLlosenord.setText("Lösenord:");

        jLlosenord1.setText("Nytt Område:");

        cbxOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("För att ändra administratörsstatus, gå tillbaka till tidigare fönster och välj \"Redigera adminstatus\"");

        jLvalAgent.setText("Välj agent:");

        cbxAgenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxAgenter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAgenterItemStateChanged(evt);
            }
        });
        cbxAgenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAgenterActionPerformed(evt);
            }
        });

        btnHamtainfo.setText("Hämta uppgifter");
        btnHamtainfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamtainfoActionPerformed(evt);
            }
        });

        jLnuvomrade.setText("Nuvarande Område:");

        btnBekrafta.setText("Bekräfta");
        btnBekrafta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBekraftaActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLtitel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLtelefon)
                                .addGap(18, 18, 18)
                                .addComponent(txtfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLlosenord)
                                    .addComponent(jLansDatum)
                                    .addComponent(jLlosenord1)
                                    .addComponent(jLnuvomrade))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfNuvomrade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLnamn)
                                .addGap(18, 18, 18)
                                .addComponent(txtfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLvalAgent)
                                    .addComponent(jLepost))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnHamtainfo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka)
                        .addGap(228, 228, 228)
                        .addComponent(btnBekrafta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLtitel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvalAgent)
                    .addComponent(cbxAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHamtainfo))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLepost)
                    .addComponent(txtfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnamn)
                    .addComponent(txtfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtelefon)
                    .addComponent(txtfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLansDatum)
                    .addComponent(txtfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLlosenord)
                    .addComponent(txtfLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnuvomrade)
                    .addComponent(txtfNuvomrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLlosenord1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBekrafta)
                    .addComponent(btnTillbaka))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxAgenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAgenterActionPerformed
        // TODO add your handling code here    
    }//GEN-LAST:event_cbxAgenterActionPerformed

    private void cbxAgenterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAgenterItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAgenterItemStateChanged

    private void btnHamtainfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamtainfoActionPerformed
        // TODO add your handling code here:
        tomAllaFalt();
        hamtaInfoAgent();
        
        if(txtfEpost.getText().equals(InlogAgent.getEpost())){
            txtfEpost.setEditable(false);
            txtfEpost.setText("");
            JOptionPane.showMessageDialog(null,"du kommer inte kunna ändra epost information om dig själv medans du är inloggad, ifall du vill ändra din epost be en annan administratör göra det");
        }
        txtfNuvomrade.setEditable(false);
    }//GEN-LAST:event_btnHamtainfoActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        new HanteraAgentAdmin(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnBekraftaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBekraftaActionPerformed
        // TODO add your handling code here:
        
        
        
        String epost = txtfEpost.getText();
        String namn = txtfNamn.getText();
        String losenord = txtfLosen.getText();
        String telefon = txtfTelefon.getText();
        String datumFalse = txtfDatum.getText();
        String [] datum = datumFalse.split("-");
        String datumTrue = datum[0]+datum[1]+datum[2];
        
        
        
        try{
            String valAgent = cbxAgenter.getSelectedItem().toString();
            String[] agent = valAgent.split("-");
            String agentid =agent[0];
            
            String valOmrade = cbxOmrade.getSelectedItem().toString();
            String[] omrade = valOmrade.split("-");
            String omradeid = omrade[0];
            
            if(Validering.isTxtFilled(epost) && Validering.isTxtFilled(namn)&&Validering.isTxtFilled(losenord)&&Validering.isTxtFilled(datumFalse)&&Validering.isTxtFilled(telefon) && Validering.containsAlphabet(namn)&&Validering.containsAlphabet(epost)&&Validering.isEpostTrustable(epost)){
                if(valOmrade.equals("Välj")){
                    String fraga = "UPDATE Agent SET Epost = '"+epost+"', Namn = '"+namn+"', Losenord = '"+losenord+"', Telefon = '"+telefon+"', Anstallningsdatum = '"+datumTrue+"' WHERE Agent_ID = "+agentid;
                    idb.update(fraga);
                    JOptionPane.showMessageDialog(null, "Agentinformation har uppdaterats!");   
                }else{
                    String fraga = "UPDATE Agent SET Epost = '"+epost+"', Namn = '"+namn+"', Losenord = '"+losenord+"', Telefon = '"+telefon+"', Anstallningsdatum = '"+datumTrue+"', Omrade = "+omradeid+" WHERE Agent_ID = "+agentid;
                    idb.update(fraga);
                    JOptionPane.showMessageDialog(null, "Agentinformation har uppdaterats!");
                }   
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Något gick fel");
            System.out.println("Intern felmed: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnBekraftaActionPerformed

    
    
private void tomAllaFalt(){
    txtfEpost.setText("");
    txtfNamn.setText("");
    txtfLosen.setText("");
    txtfTelefon.setText("");
    txtfDatum.setText("");
    txtfNuvomrade.setText("");
}    
    
private void hamtaInfoAgent(){
    
    Object valdAgent = cbxAgenter.getSelectedItem();
    String agent = valdAgent.toString();
    String[] idOchNamn = agent.split("-");
   
    
    String fraga = "SELECT * FROM Agent WHERE Agent_ID = "+idOchNamn[0];
    
    try{
        HashMap<String, String> agentInfo = idb.fetchRow(fraga);
        
        if(agentInfo !=null){
            String namn = agentInfo.get("Namn");
            if(namn != null){
                txtfNamn.setText(namn);
            }else{
                txtfNamn.setText("Info saknas");
            }
            String telefon = agentInfo.get("Telefon");
            if(telefon != null){
                txtfTelefon.setText(telefon);
            }else{
                txtfTelefon.setText("Info saknas");
            }
            String datum = agentInfo.get("Anstallningsdatum");
            if(datum != null){
                txtfDatum.setText(datum);
            }else{
                txtfDatum.setText("Info saknas");
            }
            String epost = agentInfo.get("Epost");
            if(epost != null){
                txtfEpost.setText(epost);
            }
            String losenord = agentInfo.get("Losenord");
            if(losenord != null ){
                txtfLosen.setText(losenord);
            }     
            
            
            String nuvOmradesID = agentInfo.get("Omrade");
            String omrnamn = idb.fetchSingle("SELECT benamning FROM omrade where Omrades_ID= "+nuvOmradesID);
            txtfNuvomrade.setText(omrnamn);
            
            
        }
        
    }catch(InfException ex){
        JOptionPane.showMessageDialog(null,"Något gick fel");
        System.out.println("Internt felmeddelande: "+ex.getMessage());
    }
    
    
    
}




    
    
private void laddaAgenter() {
        try {
            ArrayList<HashMap<String, String>> agentlist = idb.fetchRows("SELECT Agent_ID, Namn FROM agent");
            cbxAgenter.removeAllItems();
            for(HashMap<String, String> agent : agentlist) {
                    String agentid = agent.get("Agent_ID");
                    String namn = agent.get("Namn");
                    
                    cbxAgenter.addItem(agentid+"-"+namn);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Ett fel uppstod.");
        }
    }
            
        
private void laddaOmraden(){
    try{
        ArrayList<HashMap<String, String>> omradeList = idb.fetchRows("SELECT * FROM omrade");
        cbxOmrade.removeAllItems();
        cbxOmrade.addItem("Välj");
        for(HashMap<String, String> omrade : omradeList)
        {
            String omradeid = omrade.get("Omrades_ID");
            String namn = omrade.get("Benamning");
            cbxOmrade.addItem(omradeid+"-"+namn);
        }
        }catch(InfException ex){
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt felmed:"+ex.getMessage());
        }
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBekrafta;
    private javax.swing.JButton btnHamtainfo;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbxAgenter;
    private javax.swing.JComboBox<String> cbxOmrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLansDatum;
    private javax.swing.JLabel jLepost;
    private javax.swing.JLabel jLlosenord;
    private javax.swing.JLabel jLlosenord1;
    private javax.swing.JLabel jLnamn;
    private javax.swing.JLabel jLnuvomrade;
    private javax.swing.JLabel jLtelefon;
    private javax.swing.JLabel jLtitel;
    private javax.swing.JLabel jLvalAgent;
    private javax.swing.JTextField txtfDatum;
    private javax.swing.JTextField txtfEpost;
    private javax.swing.JTextField txtfLosen;
    private javax.swing.JTextField txtfNamn;
    private javax.swing.JTextField txtfNuvomrade;
    private javax.swing.JTextField txtfTelefon;
    // End of variables declaration//GEN-END:variables
}
