/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIB;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Melker
 */
public class SokAlienFonster extends javax.swing.JFrame {

    private static InfDB idb;
    private static ArrayList<String> platser;
    private static String valdPlats;
    private AlienManager alienManager;
    /**
     * Creates new form SokAlienFonster
     */
    public SokAlienFonster(InfDB idb) {
        initComponents();
        this.idb = idb;
        this.alienManager = new AlienManager(idb);
    }
    
    public void genereraPlatser() {
        try {
            ArrayList<String> platser = idb.fetchColumn("SELECT DISTINCT Plats FROM alien");
            for (String plats : platser) {
                valAvPlats.addItem(plats);
            }
        } catch (InfException e) {
            e.printStackTrace();
        }
    }
    
    public void hamtaAlien() {
        String valdPlats = valAvPlats.getSelectedItem().toString();
        ArrayList<Alien> aliens = alienManager.getAliensFromDB(valdPlats);
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for(Alien alien : aliens) {
            listModel.addElement(alien.getNamn());
        }
        platsLista.setModel(listModel);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sokAlien = new javax.swing.JLabel();
        sokPlatsKnapp = new javax.swing.JButton();
        valAvPlats = new javax.swing.JComboBox<>();
        sokAlienKnapp = new javax.swing.JButton();
        platsSkroll = new javax.swing.JScrollPane();
        platsLista = new javax.swing.JList<>();
        gaTillbakaKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sokAlien.setText("Sök Alien");

        sokPlatsKnapp.setText("Sök plats");
        sokPlatsKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokPlatsKnappActionPerformed(evt);
            }
        });

        sokAlienKnapp.setText("Sök Alien");
        sokAlienKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokAlienKnappActionPerformed(evt);
            }
        });

        platsSkroll.setViewportView(platsLista);

        gaTillbakaKnapp.setText("Gå tillbaka");
        gaTillbakaKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaTillbakaKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sokAlienKnapp)
                                .addComponent(valAvPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sokAlien)
                                        .addGap(178, 178, 178))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sokPlatsKnapp)
                                        .addGap(159, 159, 159))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(platsSkroll, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gaTillbakaKnapp)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sokAlien)
                .addGap(18, 18, 18)
                .addComponent(sokPlatsKnapp)
                .addGap(18, 18, 18)
                .addComponent(valAvPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sokAlienKnapp)
                .addGap(18, 18, 18)
                .addComponent(platsSkroll, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gaTillbakaKnapp)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void sokPlatsKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokPlatsKnappActionPerformed
        // TODO add your handling code here:
        genereraPlatser();
    }//GEN-LAST:event_sokPlatsKnappActionPerformed

    private void sokAlienKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokAlienKnappActionPerformed
        // TODO add your handling code here:
        hamtaAlien();
    }//GEN-LAST:event_sokAlienKnappActionPerformed

    private void gaTillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaTillbakaKnappActionPerformed
        // TODO add your handling code here:
        dispose();
        new AgentFonster(idb).setVisible(true);
    }//GEN-LAST:event_gaTillbakaKnappActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gaTillbakaKnapp;
    private javax.swing.JList<String> platsLista;
    private javax.swing.JScrollPane platsSkroll;
    private javax.swing.JLabel sokAlien;
    private javax.swing.JButton sokAlienKnapp;
    private javax.swing.JButton sokPlatsKnapp;
    private javax.swing.JComboBox<String> valAvPlats;
    // End of variables declaration//GEN-END:variables
}
