/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIB;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *klass för att ta bort utrustning helt ur systemet
 * 
 * 
 * @author alvin & adam
 */
public class TaBortUtrustning extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form TaBortUtrustning
     */
    public TaBortUtrustning(InfDB idb) {
        initComponents();
        this.idb = idb;
        setLocationRelativeTo(null);
        laddaUtrustning();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitel = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JToggleButton();
        btnTaBort = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        cbxUtrustning = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLtitel.setText("Ta bort agentutrustning");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj utrustning att ta bort:");

        cbxUtrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLtitel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLtitel)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnTaBort)
                .addGap(47, 47, 47)
                .addComponent(btnTillbaka)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AgentAdminFonster(idb).setVisible(true);
        dispose();

    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        

        try {
                //ifall inget är valt kommer meddelande
                if(cbxUtrustning.getSelectedItem().toString().equals("Välj")){
                    JOptionPane.showMessageDialog(null, "Du måste välja utrustning du vill ta bort");
                }else{
                    
                    //hämtar id för vald utrustning i cboxen
                    String IDstrang = getUtrustningsId();
                    
                    //omvandlar till int
                    int UtrID = Integer.parseInt(IDstrang);

                    //tar bort ifall det fanns med i antingen vapen, kommunikation eller teknik
                    idb.delete("DELETE FROM vapen WHERE Utrustnings_ID = " + UtrID);
                    idb.delete("DELETE FROM kommunikation WHERE Utrustnings_ID = " + UtrID);
                    idb.delete("DELETE FROM teknik WHERE Utrustnings_ID = " + UtrID);
                    
                    //tar bort ifall en agent bar på utrustningen
                    idb.delete("DELETE FROM innehar_utrustning WHERE Utrustnings_ID ="+ UtrID);
                    
                    //tar bort helt från utrustningstabellen
                    idb.delete("DELETE FROM utrustning WHERE Utrustnings_ID = " + UtrID);

                    JOptionPane.showMessageDialog(null, "Utrustningen med ID-nummer: " + UtrID + " har tagits bort från systemet!");
                    laddaUtrustning();
                }
                

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Det finns ingen utrustning med det valda ID-numret");
            System.out.println(ex.getMessage());
        }


                
    }//GEN-LAST:event_btnTaBortActionPerformed

    
//hämtar id för vald utrustning från cboxen
private String getUtrustningsId(){
    String utrustning = cbxUtrustning.getSelectedItem().toString();
    String[] allInfo = utrustning.split("-");
    String id = allInfo[0];
    return id;
}
   
//metod som laddar all utrustning i cboxen
 private void laddaUtrustning(){
     try{
         String fraga = "SELECT * FROM Utrustning";
         ArrayList<HashMap<String, String>> utrustningInfo = idb.fetchRows(fraga);
         cbxUtrustning.removeAllItems();
         cbxUtrustning.addItem("Välj");
         for(HashMap<String, String> enUtrustning : utrustningInfo){
             String id = enUtrustning.get("Utrustnings_ID");
             String namn = enUtrustning.get("Benamning");
             
             cbxUtrustning.addItem(id+"-"+namn);
         }
         
     }catch(InfException ex){
         JOptionPane.showMessageDialog(null,"Något gick fel");
         System.out.println("Internt felmed: "+ex.getMessage());
     }
 }  
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnTaBort;
    private javax.swing.JToggleButton btnTillbaka;
    private javax.swing.JComboBox<String> cbxUtrustning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLtitel;
    // End of variables declaration//GEN-END:variables
}